"""
Core Models for Intelligent Multi-Agent Orchestration.

Single source of truth for all data models.

Key design principles:
- DAG-based execution: Agent tasks are nodes in a directed acyclic graph
- Capability registry: Orchestrator discovers agents through registration, not hardcoding
- Dynamic planning: Orchestrator Agent generates DAGs at runtime via LLM
- Context isolation: Each agent has independent context, handoff via artifacts
- Event-sourced: append-only event log for session state recovery
- Artifact-centric: all state is serializable via Pydantic
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class AgentCapability(BaseModel):
    """
    Description of a Worker Agent's capabilities.
    Registered in AgentRegistry, consumed by IntelligentOrchestrator.
    """
    id: str
    name: str
    description: str
    skills: list[str] = Field(default_factory=list)
    input_schema: list[str] = Field(default_factory=list)
    output_schema: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    system_prompt: str = ""  # Optional custom system prompt for this agent


class NodeStatus(str, Enum):
    """Execution status of a DAG node."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    RETRYING = "retrying"


class NodeHealth(str, Enum):
    """Health status of a running DAG node — M2.0 heartbeat protocol."""
    HEALTHY = "healthy"       # Heartbeat within threshold
    MISSED = "missed"         # Last heartbeat > threshold but < kill_threshold
    UNHEALTHY = "unhealthy"   # Confirmed unhealthy (miss_threshold exceeded)
    DEAD = "dead"             # Killed by watchdog, final state


class DAGNode(BaseModel):
    """
    A single node in the execution DAG = one agent task.
    """
    id: str
    agent_type: str           # References AgentCapability.id
    task_description: str
    status: NodeStatus = NodeStatus.PENDING
    result: dict[str, Any] = Field(default_factory=dict)
    error: str = ""
    output_artifacts: list[str] = Field(default_factory=list)
    success_criteria: list[str] = Field(default_factory=list)
    eval_feedback: str = ""  # Evaluator feedback, passed back on retry
    max_retries: int = 3
    retry_count: int = 0
    started_at: datetime | None = None
    completed_at: datetime | None = None

    # M2.0: Heartbeat fields
    health_status: NodeHealth = NodeHealth.HEALTHY  # Current health
    last_heartbeat_at: datetime | None = None       # Last heartbeat timestamp
    heartbeat_count: int = 0                         # Total heartbeats received
    missed_heartbeats: int = 0                       # Consecutive missed beats

    def record_heartbeat(self) -> None:
        """Record a heartbeat from the executing agent."""
        self.last_heartbeat_at = datetime.now(timezone.utc)
        self.heartbeat_count += 1
        if self.missed_heartbeats > 0:
            self.missed_heartbeats = 0  # Reset on successful heartbeat
        if self.health_status in (NodeHealth.MISSED, NodeHealth.UNHEALTHY):
            self.health_status = NodeHealth.HEALTHY  # Recovery

    def check_health(self, heartbeat_interval_sec: float = 5.0,
                     miss_threshold: int = 3) -> NodeHealth:
        """
        Check current health based on last heartbeat.

        Returns:
            HEALTHY: Last heartbeat within interval
            MISSED: 1+ missed beats but below threshold
            UNHEALTHY: miss_threshold exceeded → should be killed
        """
        if self.status != NodeStatus.RUNNING:
            return self.health_status  # Only check running nodes

        if self.last_heartbeat_at is None:
            # Never sent heartbeat since starting
            if self.started_at is None:
                return self.health_status
            elapsed = (datetime.now(timezone.utc) - self.started_at).total_seconds()
        else:
            elapsed = (datetime.now(timezone.utc) - self.last_heartbeat_at).total_seconds()

        missed = int(elapsed / heartbeat_interval_sec)
        self.missed_heartbeats = max(self.missed_heartbeats, missed)

        if missed >= miss_threshold:
            self.health_status = NodeHealth.UNHEALTHY
        elif missed >= 1:
            self.health_status = NodeHealth.MISSED
        else:
            self.health_status = NodeHealth.HEALTHY

        return self.health_status

    def model_post_init(self, __context: Any) -> None:
        if not self.id:
            self.id = f"node_{uuid.uuid4().hex[:8]}"


class DAGEdge(BaseModel):
    """A directed edge from one node to another."""
    from_node: str
    to_node: str


class DAG(BaseModel):
    """
    Directed Acyclic Graph = execution plan.
    Generated by IntelligentOrchestrator, executed by DAGExecutionEngine.
    """
    nodes: dict[str, DAGNode] = Field(default_factory=dict)
    edges: list[DAGEdge] = Field(default_factory=list)
    reasoning: str = ""  # Orchestrator's reasoning for this plan

    def add_node(self, node: DAGNode) -> None:
        self.nodes[node.id] = node

    def add_edge(self, from_id: str, to_id: str) -> None:
        self.edges.append(DAGEdge(from_node=from_id, to_node=to_id))

    def get_dependencies(self, node_id: str) -> list[str]:
        """Get all predecessor nodes."""
        return [e.from_node for e in self.edges if e.to_node == node_id]

    def get_dependents(self, node_id: str) -> list[str]:
        """Get all successor nodes."""
        return [e.to_node for e in self.edges if e.from_node == node_id]

    def topological_levels(self) -> list[list[str]]:
        """
        Return topological sort as levels.
        Nodes in the same level have no dependencies between each other
        and can be executed in parallel.
        """
        in_degree = {nid: 0 for nid in self.nodes}
        adj = {nid: [] for nid in self.nodes}

        for edge in self.edges:
            adj[edge.from_node].append(edge.to_node)
            in_degree[edge.to_node] += 1

        levels = []
        remaining = set(self.nodes.keys())

        while remaining:
            # Find all nodes with in-degree 0
            current_level = [
                nid for nid in remaining
                if in_degree[nid] == 0
            ]
            if not current_level:
                raise ValueError("Cycle detected in DAG")

            levels.append(current_level)
            remaining -= set(current_level)

            # Remove current level from graph
            for nid in current_level:
                for dependent in adj[nid]:
                    in_degree[dependent] -= 1

        return levels

    def get_ready_nodes(self) -> list[str]:
        """Get nodes whose dependencies are all satisfied."""
        ready = []
        for nid, node in self.nodes.items():
            if node.status != NodeStatus.PENDING:
                continue
            deps = self.get_dependencies(nid)
            if all(self.nodes[d].status == NodeStatus.SUCCESS for d in deps):
                ready.append(nid)
        return ready


class ExecutionEvent(BaseModel):
    """An event during DAG execution."""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    node_id: str
    event_type: Literal[
        "started", "completed", "failed", "retrying", "skipped",
        "heartbeat", "heartbeat_missed", "unhealthy_killed", "health_recovered",
        "health_alert", "upstream_retry",
    ]
    details: dict[str, Any] = Field(default_factory=dict)


class FailureDecision(BaseModel):
    """Orchestrator's decision on how to handle a failed node."""
    action: Literal["retry", "skip", "abort", "replan"]
    reasoning: str = ""
    # For replan: new DAG or modifications
    modifications: dict[str, Any] = Field(default_factory=dict)


class OrchestratorPlan(BaseModel):
    """Output of the orchestrator agent's planning phase."""
    reasoning: str
    nodes: list[dict[str, Any]]
    edges: list[dict[str, str]]


class HandoffArtifact(BaseModel):
    """
    Structured handoff between agents.
    Each agent's output becomes the next agent's input.
    """
    from_agent: str
    to_agent: str
    content: str = ""                    # Human-readable summary
    file_paths: list[str] = Field(default_factory=list)  # Generated files
    metadata: dict[str, Any] = Field(default_factory=dict)  # Structured data
    created_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================================
# =============================================================================
# Foundational models
# =============================================================================
# =============================================================================


class EventType(str, Enum):
    """Event types following {domain}.{action} convention."""
    # User events
    USER_MESSAGE = "user.message"
    USER_COMMAND = "user.command"

    # Agent events
    AGENT_MESSAGE = "agent.message"
    AGENT_TOOL_USE = "agent.tool_use"
    AGENT_TOOL_RESULT = "agent.tool_result"
    AGENT_ERROR = "agent.error"

    # Session events
    SESSION_START = "session.status_start"
    SESSION_IDLE = "session.status_idle"
    SESSION_RUNNING = "session.status_running"
    SESSION_ERROR = "session.status_error"
    SESSION_END = "session.status_end"

    # Workflow events
    WORKFLOW_STAGE_START = "workflow.stage_start"
    WORKFLOW_STAGE_END = "workflow.stage_end"
    WORKFLOW_STAGE_ERROR = "workflow.stage_error"

    # Tool events
    TOOL_EXEC_START = "tool.exec_start"
    TOOL_EXEC_END = "tool.exec_end"
    TOOL_EXEC_ERROR = "tool.exec_error"

    # Evaluation events
    EVAL_START = "eval.start"
    EVAL_RESULT = "eval.result"
    EVAL_CONTRACT_CHECK = "eval.contract_check"

    # Checkpoint events
    CHECKPOINT_CREATED = "checkpoint.created"
    CHECKPOINT_RESTORED = "checkpoint.restored"

    # Memory events (M3.2)
    MEMORY_STORED = "memory.stored"
    MEMORY_ACCESSED = "memory.accessed"
    MEMORY_SHARED = "memory.shared"
    MEMORY_EXPIRED = "memory.expired"
    MEMORY_PRUNED = "memory.pruned"

    # Learning events (M3.3)
    LEARNING_ANALYSIS_START = "learning.analysis_start"
    LEARNING_INSIGHT_GENERATED = "learning.insight_generated"
    LEARNING_OPTIMIZATION_APPLIED = "learning.optimization_applied"


class Event(BaseModel):
    """Immutable event in the session log."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    type: EventType
    session_id: str
    payload: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseModel):
    """A tool call from the agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class ToolResult(BaseModel):
    """Result of a tool execution."""
    tool_call_id: str
    success: bool
    output: str = ""
    error: str = ""
    duration_ms: int = 0


class AgentMessage(BaseModel):
    """Message from/to the agent."""
    role: Literal["system", "user", "assistant", "tool"]
    content: str
    tool_calls: list[ToolCall] = Field(default_factory=list)
    tool_call_id: str | None = None


class SessionMetrics(BaseModel):
    """Runtime metrics for a session."""
    total_events: int = 0
    total_tool_calls: int = 0
    total_tokens_input: int = 0
    total_tokens_output: int = 0
    total_duration_ms: int = 0
    stage_durations: dict[str, int] = Field(default_factory=dict)
    errors: list[str] = Field(default_factory=list)


class SessionState(BaseModel):
    """Recoverable session state derived from event log."""
    session_id: str
    created_at: datetime
    status: Literal["created", "running", "idle", "error", "completed"] = "created"
    current_stage: str | None = None
    stages_completed: list[str] = Field(default_factory=list)
    artifacts: dict[str, str] = Field(default_factory=dict)
    context_window: list[AgentMessage] = Field(default_factory=list)
    metrics: SessionMetrics = Field(default_factory=SessionMetrics)


class RiskLevel(int, Enum):
    """Risk classification for operations."""
    LOW = 1       # Read-only, safe
    MEDIUM = 2    # File edits, reversible
    HIGH = 3      # Bash commands, network access
    CRITICAL = 4  # Irreversible, production impact


class PermissionMode(str, Enum):
    """Permission modes."""
    PLAN = "plan"                    # Read-only
    DEFAULT = "default"              # Ask for every action
    ACCEPT_EDITS = "accept_edits"    # Auto-approve file edits
    AUTO = "auto"                    # Classifier-based approval
    DONT_ASK = "dont_ask"            # Only pre-approved tools


class GuardrailPolicy(BaseModel):
    """Policy configuration for guardrails."""
    mode: PermissionMode = PermissionMode.DEFAULT
    allowed_tools: list[str] = Field(default_factory=list)
    denied_tools: list[str] = Field(default_factory=list)
    allowed_commands: list[str] = Field(default_factory=list)
    denied_commands: list[str] = Field(default_factory=list)
    max_bash_duration: int = 120
    max_iterations: int = 50
    auto_approve_read: bool = True
    require_human_on_error: bool = True


class PersonalGuardrailPolicy(GuardrailPolicy):
    """个人模式专用护栏策略。

    LOW/MEDIUM: 自动通过
    HIGH: 需要确认（或命中白名单自动通过）
    CRITICAL: 始终需要确认
    """
    # 白名单：命令前缀或正则列表
    whitelist_patterns: list[str] = Field(default_factory=list)
    # 自动确认的白名单命令
    whitelist_commands: list[str] = Field(default_factory=list)
    # HIGH 风险是否自动通过（个人模式下不推荐，但可配置）
    auto_approve_high: bool = False
    # 交互式确认超时（秒），超时则拒绝
    confirmation_timeout_sec: int = 300


class EvaluationResult(BaseModel):
    """Result of an evaluation pass."""
    passed: bool
    score: float = 0.0
    criteria_results: dict[str, bool] = Field(default_factory=dict)
    feedback: str = ""
    suggestions: list[str] = Field(default_factory=list)


# =============================================================================
# M3.2: Agent Memory models
# =============================================================================


class MemoryScope(str, Enum):
    """Visibility scope of a memory entry."""
    PRIVATE = "private"      # Per-agent, only the owning agent sees it
    SESSION = "session"      # Shared among agents within one session
    GLOBAL = "global"        # Cross-session, cross-agent, persistent


class MemoryType(str, Enum):
    """Classification of memory content."""
    FACT = "fact"            # Learned knowledge (e.g., "project uses pytest")
    EXPERIENCE = "experience"  # Task outcome (e.g., "planner succeeded with linear DAG")
    PREFERENCE = "preference"  # User preference (e.g., "user prefers type hints")
    CONTEXT = "context"      # Project context (e.g., "entry point is main.py")


class MemoryEntry(BaseModel):
    """A single memory record persisted across agent executions."""
    id: str = Field(default_factory=lambda: f"mem_{uuid.uuid4().hex[:12]}")
    agent_type: str           # Owning agent (planner/generator/evaluator or "shared")
    scope: MemoryScope = MemoryScope.PRIVATE
    memory_type: MemoryType = MemoryType.FACT
    content: str
    keywords: list[str] = Field(default_factory=list)
    session_id: str | None = None
    source_node_id: str | None = None
    access_count: int = 0
    relevance_score: float = 1.0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_accessed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


# =============================================================================
# M3.3: Self-Learning models
# =============================================================================


class LearningCategory(str, Enum):
    """Category of a learning insight."""
    PLANNING = "planning"
    EXECUTION = "execution"
    EVALUATION = "evaluation"
    AGENT_SELECTION = "agent_selection"


class InsightType(str, Enum):
    """Type of learning insight."""
    PATTERN = "pattern"              # Positive pattern to replicate
    RECOMMENDATION = "recommendation"  # Suggested improvement
    ANTI_PATTERN = "anti_pattern"     # Negative pattern to avoid


class LearningInsight(BaseModel):
    """A learning insight extracted from execution history analysis."""
    id: str = Field(default_factory=lambda: f"ins_{uuid.uuid4().hex[:12]}")
    category: LearningCategory
    insight_type: InsightType
    description: str
    evidence: dict[str, Any] = Field(default_factory=dict)
    confidence: float = 1.0          # 0.0 to 1.0
    impact: Literal["low", "medium", "high"] = "medium"
    applies_to: list[str] = Field(default_factory=list)  # Agent types
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)
