"""
Core Models for Intelligent Multi-Agent Orchestration.

Single source of truth for all data models.

Key design principles:
- DAG-based execution: Agent tasks are nodes in a directed acyclic graph
- Capability registry: Orchestrator discovers agents through registration, not hardcoding
- Dynamic planning: Orchestrator Agent generates DAGs at runtime via LLM
- Context isolation: Each agent has independent context, handoff via artifacts
- Event-sourced: append-only event log for session state recovery
- Artifact-centric: all state is serializable via Pydantic
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class AgentCapability(BaseModel):
    """
    Description of a Worker Agent's capabilities.
    Registered in AgentRegistry, consumed by IntelligentOrchestrator.
    """
    id: str
    name: str
    description: str
    skills: list[str] = Field(default_factory=list)
    input_schema: list[str] = Field(default_factory=list)
    output_schema: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    system_prompt: str = ""  # Optional custom system prompt for this agent


class NodeStatus(str, Enum):
    """Execution status of a DAG node."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    RETRYING = "retrying"


class DAGNode(BaseModel):
    """
    A single node in the execution DAG = one agent task.
    """
    id: str
    agent_type: str           # References AgentCapability.id
    task_description: str
    status: NodeStatus = NodeStatus.PENDING
    result: dict[str, Any] = Field(default_factory=dict)
    error: str = ""
    output_artifacts: list[str] = Field(default_factory=list)
    max_retries: int = 3
    retry_count: int = 0
    started_at: datetime | None = None
    completed_at: datetime | None = None

    def model_post_init(self, __context: Any) -> None:
        if not self.id:
            self.id = f"node_{uuid.uuid4().hex[:8]}"


class DAGEdge(BaseModel):
    """A directed edge from one node to another."""
    from_node: str
    to_node: str


class DAG(BaseModel):
    """
    Directed Acyclic Graph = execution plan.
    Generated by IntelligentOrchestrator, executed by DAGExecutionEngine.
    """
    nodes: dict[str, DAGNode] = Field(default_factory=dict)
    edges: list[DAGEdge] = Field(default_factory=list)
    reasoning: str = ""  # Orchestrator's reasoning for this plan

    def add_node(self, node: DAGNode) -> None:
        self.nodes[node.id] = node

    def add_edge(self, from_id: str, to_id: str) -> None:
        self.edges.append(DAGEdge(from_node=from_id, to_node=to_id))

    def get_dependencies(self, node_id: str) -> list[str]:
        """Get all predecessor nodes."""
        return [e.from_node for e in self.edges if e.to_node == node_id]

    def get_dependents(self, node_id: str) -> list[str]:
        """Get all successor nodes."""
        return [e.to_node for e in self.edges if e.from_node == node_id]

    def topological_levels(self) -> list[list[str]]:
        """
        Return topological sort as levels.
        Nodes in the same level have no dependencies between each other
        and can be executed in parallel.
        """
        in_degree = {nid: 0 for nid in self.nodes}
        adj = {nid: [] for nid in self.nodes}

        for edge in self.edges:
            adj[edge.from_node].append(edge.to_node)
            in_degree[edge.to_node] += 1

        levels = []
        remaining = set(self.nodes.keys())

        while remaining:
            # Find all nodes with in-degree 0
            current_level = [
                nid for nid in remaining
                if in_degree[nid] == 0
            ]
            if not current_level:
                raise ValueError("Cycle detected in DAG")

            levels.append(current_level)
            remaining -= set(current_level)

            # Remove current level from graph
            for nid in current_level:
                for dependent in adj[nid]:
                    in_degree[dependent] -= 1

        return levels

    def get_ready_nodes(self) -> list[str]:
        """Get nodes whose dependencies are all satisfied."""
        ready = []
        for nid, node in self.nodes.items():
            if node.status != NodeStatus.PENDING:
                continue
            deps = self.get_dependencies(nid)
            if all(self.nodes[d].status == NodeStatus.SUCCESS for d in deps):
                ready.append(nid)
        return ready


class ExecutionEvent(BaseModel):
    """An event during DAG execution."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    node_id: str
    event_type: Literal["started", "completed", "failed", "retrying", "skipped"]
    details: dict[str, Any] = Field(default_factory=dict)


class FailureDecision(BaseModel):
    """Orchestrator's decision on how to handle a failed node."""
    action: Literal["retry", "skip", "abort", "replan"]
    reasoning: str = ""
    # For replan: new DAG or modifications
    modifications: dict[str, Any] = Field(default_factory=dict)


class OrchestratorPlan(BaseModel):
    """Output of the orchestrator agent's planning phase."""
    reasoning: str
    nodes: list[dict[str, Any]]
    edges: list[dict[str, str]]


class HandoffArtifact(BaseModel):
    """
    Structured handoff between agents.
    Each agent's output becomes the next agent's input.
    """
    from_agent: str
    to_agent: str
    content: str = ""                    # Human-readable summary
    file_paths: list[str] = Field(default_factory=list)  # Generated files
    metadata: dict[str, Any] = Field(default_factory=dict)  # Structured data
    created_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================================
# =============================================================================
# Foundational models
# =============================================================================
# =============================================================================


class EventType(str, Enum):
    """Event types following {domain}.{action} convention."""
    # User events
    USER_MESSAGE = "user.message"
    USER_COMMAND = "user.command"

    # Agent events
    AGENT_MESSAGE = "agent.message"
    AGENT_TOOL_USE = "agent.tool_use"
    AGENT_TOOL_RESULT = "agent.tool_result"
    AGENT_ERROR = "agent.error"

    # Session events
    SESSION_START = "session.status_start"
    SESSION_IDLE = "session.status_idle"
    SESSION_RUNNING = "session.status_running"
    SESSION_ERROR = "session.status_error"
    SESSION_END = "session.status_end"

    # Workflow events
    WORKFLOW_STAGE_START = "workflow.stage_start"
    WORKFLOW_STAGE_END = "workflow.stage_end"
    WORKFLOW_STAGE_ERROR = "workflow.stage_error"

    # Tool events
    TOOL_EXEC_START = "tool.exec_start"
    TOOL_EXEC_END = "tool.exec_end"
    TOOL_EXEC_ERROR = "tool.exec_error"

    # Evaluation events
    EVAL_START = "eval.start"
    EVAL_RESULT = "eval.result"
    EVAL_CONTRACT_CHECK = "eval.contract_check"

    # Checkpoint events
    CHECKPOINT_CREATED = "checkpoint.created"
    CHECKPOINT_RESTORED = "checkpoint.restored"


class Event(BaseModel):
    """Immutable event in the session log."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    type: EventType
    session_id: str
    payload: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolCall(BaseModel):
    """A tool call from the agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class ToolResult(BaseModel):
    """Result of a tool execution."""
    tool_call_id: str
    success: bool
    output: str = ""
    error: str = ""
    duration_ms: int = 0


class AgentMessage(BaseModel):
    """Message from/to the agent."""
    role: Literal["system", "user", "assistant", "tool"]
    content: str
    tool_calls: list[ToolCall] = Field(default_factory=list)
    tool_call_id: str | None = None


class SessionMetrics(BaseModel):
    """Runtime metrics for a session."""
    total_events: int = 0
    total_tool_calls: int = 0
    total_tokens_input: int = 0
    total_tokens_output: int = 0
    total_duration_ms: int = 0
    stage_durations: dict[str, int] = Field(default_factory=dict)
    errors: list[str] = Field(default_factory=list)


class SessionState(BaseModel):
    """Recoverable session state derived from event log."""
    session_id: str
    created_at: datetime
    status: Literal["created", "running", "idle", "error", "completed"] = "created"
    current_stage: str | None = None
    stages_completed: list[str] = Field(default_factory=list)
    artifacts: dict[str, str] = Field(default_factory=dict)
    context_window: list[AgentMessage] = Field(default_factory=list)
    metrics: SessionMetrics = Field(default_factory=SessionMetrics)


class RiskLevel(int, Enum):
    """Risk classification for operations."""
    LOW = 1       # Read-only, safe
    MEDIUM = 2    # File edits, reversible
    HIGH = 3      # Bash commands, network access
    CRITICAL = 4  # Irreversible, production impact


class PermissionMode(str, Enum):
    """Permission modes."""
    PLAN = "plan"                    # Read-only
    DEFAULT = "default"              # Ask for every action
    ACCEPT_EDITS = "accept_edits"    # Auto-approve file edits
    AUTO = "auto"                    # Classifier-based approval
    DONT_ASK = "dont_ask"            # Only pre-approved tools


class GuardrailPolicy(BaseModel):
    """Policy configuration for guardrails."""
    mode: PermissionMode = PermissionMode.DEFAULT
    allowed_tools: list[str] = Field(default_factory=list)
    denied_tools: list[str] = Field(default_factory=list)
    allowed_commands: list[str] = Field(default_factory=list)
    denied_commands: list[str] = Field(default_factory=list)
    max_bash_duration: int = 120
    max_iterations: int = 50
    auto_approve_read: bool = True
    require_human_on_error: bool = True


class EvaluationResult(BaseModel):
    """Result of an evaluation pass."""
    passed: bool
    score: float = 0.0
    criteria_results: dict[str, bool] = Field(default_factory=dict)
    feedback: str = ""
    suggestions: list[str] = Field(default_factory=list)
